stages:
  - unit_tests
  - test_flight
  - archive

cache:
  paths:
    - Carthage/

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - gem install bundler
  - bundle install

run_tests:
  stage: unit_tests
  script: bundle exec fastlane test
  tags:
    - ios

build_test_flight:
  stage: test_flight
  script: bundle exec fastlane beta
  tags:
    - ios
  only:
    - /^release-.*$/
    - develop

build_archive:
  stage: archive
  script: bundle exec fastlane deploy
  only:
    - /^release-.*$/
    - develop
  artifacts:
    paths:
      - build/CoinKeeper.ipa
    expire_in: 4 weeks
  tags:
    - ios
  when: manual
